site_name: Signal

site_url: https://signal.iso8583.tech

extra_css:
  - stylesheets/extra.css

#docs_dir: docs/pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - attr_list
  - pymdownx.snippets:
        base_path: docs
  - pymdownx.highlight:
      pygments_lang_class: true
      anchor_linenums: true
      line_spans: __span

theme:
  name: material
  logo: images/logo_triangle.ico
  favicon: images/logo_triangle.ico
  palette:
    primary: blue grey
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.indexes
    - navigation.path

plugins:
  - social

nav:
  - General:
    - general/index.md
    - Overview: general/overview.md
    - Release info: general/release-info.md
    - Bugs: general/bugs.md
    - Licence: general/license.md
    - Author: general/author.md
  - Desktop:
    - gui/index.md
    - Features:
        - Transactions: gui/features/transactions.md
        - Data exchange: gui/features/data_exchange.md
        - Validations: gui/features/validations.md
        - Search line: gui/features/search_line.md
        - Hide secrets: gui/features/hide_secrets.md
        - Hotkeys: gui/features/hotkeys.md
    - Tools:
      - Connector: gui/tools/connector.md
      - Echo-test: gui/tools/echo_test.md
      - Keep alive: gui/tools/keep_alive.md
      - Transactions auto-repeat: gui/tools/repeat.md
      - Reversal: gui/tools/reversal.md
      - Complex fields parser: gui/tools/fields_parser.md
      - Print data: gui/tools/print_data.md
      - Fields generators: gui/tools/fields_generators.md
      - Secret features: gui/tools/secret_features.md
    - Settings:
      - General: gui/settings/general.md
      - Fields: gui/settings/fields.md
      - Specification: gui/settings/specification.md
      - API: gui/settings/api.md
  - Command Line:
      - cli/index.md
      - Commands: cli/commands.md
      - Combinations: cli/combinations.md
      - Command line API: cli/cli_api.md
  - HTTP API: todo.md
  - Python library: todo2.md
  - Data models:
      - data_models/index.md
      - Transaction: data_models/transaction.md
      - Specification: data_models/specification.md
      - Config: data_models/config.md
      - Validations: data_models/validations.md
      - Dictionaries: data_models/dictionaries.md
  - Download: downloads.md
