site_name: Signal

site_url: https://signal.iso8583.tech

theme:
  name: material
  logo: images/logo_triangle.ico
  favicon: images/logo_triangle.ico


nav:
  - General: index.md
  - Overview: overview.md
  - Release info: release-info.md
  - Downloads: downloads.md
